require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# Configuración estándar para silenciar advertencias
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # ESTA es la línea correcta. Sin "use_", sin "config =", solo esto:
  capacitor_pods
end

post_install do |installer|
  capacitor_pods_post_install(installer)
end